### PR TITLE
Increase height of description fields for implementation of requirements/safeguards

### PR DESCRIPTION
**Pull request by C1710**
When doing an IT-Grundschutz Check/Basic Security Check, it is crucial to properly document the implementation status of the requirements/safeguards beyond a simple "yes"/"partially"/"no"/"unnecessary".
Right now, that particular field is rather small in Verinice, which makes it hard to use the description field.  
With this PR, this field (both in the 100-x and 200-x views) is increased to 10 lines (instead of the default of 4), similar to the text fields for audits.
It may be worth considering to make this field even larger, but that would be inconsistent to other text fields and it might become too large in some cases.

### CODE REVIEW

**Comment by murygin** [comment]
Please split this pull request. In this PR should be only the change of the text field. Please put the addition of the Docker file into an extra PR.

**Comment by C1710** [comment]
> Please split this pull request. In this PR should be only the change of the text field. Please put the addition of the Docker file into an extra PR.

Sorry, I didn't intend to add it to the PR, I'll remove it later

**Comment by murygin** [comment]
Please make the same change in the file [sernet.gs.server/testSrc/SNCA.xml](https://github.com/SerNet/verinice/blob/master/sernet.gs.server/testSrc/SNCA.xml). Both files must always be the same.

**Comment by murygin** [comment]
I have now approved your change. The change has been applied to the development branch on our internal build system. With the next release verinice 1.27 the change will be published, probably in December 2023. Thank you for your contribution!

We use GitHub only for the source code of released finished versions. Only the master branch and tags are pushed here, but not feature and the development branch. For this reason, the pull request will not be merged yet, but only after the release of verinice 1.27.

**Comment by murygin** [comment]
I have now approved your change. The change has been applied to the development branch on our internal build system. With the next release verinice 1.27 the change will be published, probably in December 2023. Thank you for your contribution!

We use GitHub only for the source code of released finished versions. Only the master branch and tags are pushed here, but not feature and the development branch. For this reason, the pull request is not merged now but closed even though your change was accepted.

**Pull request closed without merging**
